/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: chelC (https://sketchfab.com/chelC)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cellphone-06392fcec89d4b729a973e1aaab40a41
Title: Cellphone
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useHelper } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { MathUtils, BoxHelper } from "three";

export function Cell(props) {
  const light = useRef();
  const { nodes, materials } = useGLTF("models/cellphone.glb");
  useHelper(light, BoxHelper, "red");

  return (
    <group dispose={null} scale={[0.048, 0.048, 0.048]}>
      <group
        position-y={2.3}
        position-z={0.4}
        position-x={0.8}
        rotation-z={-MathUtils.degToRad(65)}
        rotation-y={MathUtils.degToRad(40)}
      >
        <mesh
          geometry={nodes.pCube1_black_0.geometry}
          material={materials.black}
        />
        <mesh
          geometry={nodes.pCube1_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.pCube1_glow_0.geometry}
          material={materials.glow}
        />
        <mesh
          geometry={nodes.pCube1_lambert4_0.geometry}
          material={materials.lambert4}
        />
        <mesh
          geometry={nodes.pCube4_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.pCube2_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.pCylinder1_black_0.geometry}
          material={materials.black}
        />
        <mesh
          geometry={nodes.pCube3_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.pCube5_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.pCylinder2_black_0.geometry}
          material={materials.black}
        />
        <mesh
          geometry={nodes.pCylinder2_glow_0.geometry}
          material={materials.glow}
        />
        <mesh
          geometry={nodes.pCylinder3_black_0.geometry}
          material={materials.black}
        />
        <mesh
          geometry={nodes.pCylinder4_glow_0.geometry}
          material={materials.glow}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/cellphone.glb");
